sudo: required
services:
  - docker

before_install:
  - docker build -t maurilioferreira/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maurilioferreira/react-test npm test

after_success:
  - docker build -t maurilioferreira/multi-client ./client
  - docker build -t maurilioferreira/multi-nginx ./nginx
  - docker build -t maurilioferreira/multi-server ./server
  - docker build -t maurilioferreira/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push maurilioferreira/multi-client
  - docker push maurilioferreira/multi-nginx
  - docker push maurilioferreira/multi-server
  - docker push maurilioferreira/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-955278487331
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY
#deploy:
# edge: true
# provider: elasticbeanstalk